/**
 * Builds the wordmark and monogram as SVG outlines from Bodoni Moda (SIL OFL),
 * so the logo renders identically everywhere without loading the font.
 *
 *   cd scripts && npm install && npm run logo
 *
 * Writes src/components/ui/logo-paths.ts. Two optical sizes are generated: a
 * sturdier cut for the header (opsz 30) and a high-contrast cut for display use.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as fontkit from "fontkit";

const here = path.dirname(fileURLToPath(import.meta.url));
const cache = path.join(here, ".cache");
const out = path.resolve(here, "../../src/components/ui/logo-paths.ts");

const FONTS = {
  roman: "https://github.com/google/fonts/raw/main/ofl/bodonimoda/BodoniModa%5Bopsz,wght%5D.ttf",
  italic: "https://github.com/google/fonts/raw/main/ofl/bodonimoda/BodoniModa-Italic%5Bopsz,wght%5D.ttf",
};

async function font(name) {
  const file = path.join(cache, `${name}.ttf`);
  if (!fs.existsSync(file)) {
    fs.mkdirSync(cache, { recursive: true });
    const res = await fetch(FONTS[name]);
    if (!res.ok) throw new Error(`Could not download ${name}: ${res.status}`);
    fs.writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  return fontkit.openSync(file);
}

const roman = await font("roman");
const italic = await font("italic");
const r2 = (n) => Math.round(n * 100) / 100;
// Round path coordinates to keep the payload small
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => String(r2(parseFloat(n))));

function glyphRun(face, text, { size, tracking, wght, opsz, x0, baseline }) {
  const v = face.getVariation({ wght, opsz });
  const scale = size / v.unitsPerEm;
  const run = v.layout(text);
  let x = x0;
  const paths = [];
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  run.glyphs.forEach((g, i) => {
    const pos = run.positions[i];
    const p = g.path.scale(scale, -scale).translate(x + pos.xOffset * scale, baseline - pos.yOffset * scale);
    const b = p.bbox;
    minX = Math.min(minX, b.minX); maxX = Math.max(maxX, b.maxX);
    minY = Math.min(minY, b.minY); maxY = Math.max(maxY, b.maxY);
    paths.push(p.toSVG());
    x += pos.xAdvance * scale + tracking * size;
  });
  return { d: paths.join(""), end: x - tracking * size, bbox: { minX, maxX, minY, maxY }, capHeight: v.capHeight * scale };
}

/** "JUST · BECHO" — the dot is drawn by the component as a small diamond. */
function wordmark(opsz, wght) {
  const size = 100, tracking = 0.16, gap = 46;
  const a = glyphRun(roman, "JUST", { size, tracking, wght, opsz, x0: 0, baseline: 100 });
  const b = glyphRun(roman, "BECHO", { size, tracking, wght, opsz, x0: a.end + gap, baseline: 100 });
  const minX = Math.min(a.bbox.minX, b.bbox.minX), maxX = Math.max(a.bbox.maxX, b.bbox.maxX);
  const minY = Math.min(a.bbox.minY, b.bbox.minY), maxY = Math.max(a.bbox.maxY, b.bbox.maxY);
  const dot = { cx: r2(a.end + gap / 2), cy: r2(100 - a.capHeight / 2), r: 3.6 };
  return { viewBox: `${r2(minX)} ${r2(minY)} ${r2(maxX - minX)} ${r2(maxY - minY)}`, d: round(a.d + b.d), dot };
}

/** An upright B crossed by an italic J, centred in a 300 × 300 seal. */
function monogram() {
  const B = glyphRun(roman, "B", { size: 250, tracking: 0, wght: 520, opsz: 72, x0: 0, baseline: 0 });
  const J = glyphRun(italic, "J", { size: 290, tracking: 0, wght: 480, opsz: 72, x0: 0, baseline: 0 });
  const bx = 150 - (B.bbox.maxX - B.bbox.minX) / 2 - B.bbox.minX + 22, by = 150 + B.capHeight / 2;
  const jx = 150 - (J.bbox.maxX - J.bbox.minX) / 2 - J.bbox.minX - 34, jy = 150 + J.capHeight / 2 - 10;
  return { b: round(B.d), bT: [r2(bx), r2(by)], j: round(J.d), jT: [r2(jx), r2(jy)] };
}

const exports = {
  WORDMARK_TEXT: wordmark(30, 480),
  WORDMARK_DISPLAY: wordmark(96, 440),
  MONOGRAM: monogram(),
};
const body = Object.entries(exports)
  .map(([name, value]) => `export const ${name} = ${JSON.stringify(value)} as const;`)
  .join("\n\n");
fs.writeFileSync(out, `/* Generated by scripts/logo/build.mjs from Bodoni Moda (SIL OFL) outlines. Do not edit by hand. */\n\n${body}\n`);
console.log(`Wrote ${path.relative(process.cwd(), out)} (${(body.length / 1024).toFixed(1)} KB)`);
