/* Generated by scripts/studio/compose.mjs: background-removed product shots composited on the house backdrop. */

export interface StudioEntry {
  blur: string;
  figure: boolean;
  box: { x: number; y: number; w: number; h: number };
  cutAspect: number;
}

export const STUDIO: Record<string, StudioEntry> = {
 "hermes-kelly-28-sellier-bleu-paon": {
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZgC06CHhX8nSvslxgAD+6oDLtVrea8+Tf9TbCQVwk7QkuHebKxVvatCIYed+uthv5FJt8G7Pmu7unqaUBAAA",
  "figure": false,
  "box": {
   "x": 0.1925,
   "y": 0.2,
   "w": 0.615,
   "h": 0.6
  },
  "cutAspect": 0.8307
 },
 "louis-vuitton-speedy-bandouliere-25-monogram": {
  "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZQC7ACHhULir3CiAAP7qgKdqTe99reREbNu/MzfVPCb300jDS8qxERFbmSxDofA7U8noyYoPZaIT6+7NmBgwQ3LXknqAAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.2105,
   "w": 0.72,
   "h": 0.5895
  },
  "cutAspect": 0.9775
 },
 "dior-vibe-zip-bowling-bag-medium": {
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoQABQAPu1kqU2ppaQiMAgBMB2JZQC06CHhTPzsslgA/uqAKQppTmJeQkclVULjXRkDbVFtzDLUd8MvzbtkUcEDyirJsu8ziAAAAA==",
  "figure": false,
  "box": {
   "x": 0.1656,
   "y": 0.2,
   "w": 0.6688,
   "h": 0.6
  },
  "cutAspect": 0.8949
 },
 "gucci-gg-marmont-small-matelasse-black": {
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAAW+9pLrMkhC8AAP7qgBHTjgIjHMZyoI7WYGPz7B91+PKG8mCPf50LBOyk8O9UYutmBhpanQM4CxIYAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.397,
   "w": 0.72,
   "h": 0.403
  },
  "cutAspect": 1.408
 },
 "saint-laurent-envelope-medium-red": {
  "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoQABQAPu1iqU2ppaQiMAgBMB2JbACdMoAlnxffwcMFeU/b19UB5sAA/uqP+pztj+FL1BcK8497HHwtPxpMjCRlvmNSjZTq1rDyO4jUMullJVHQJE8KL3MaaVQtxIPbQjmMrkJh/OV0z/IssFF1Ettfn/1EXdJm8+HipywRxXRDU0mRr/L5ia1pnR2uY2v9kxIWakgQAAA=",
  "figure": true,
  "box": {
   "x": 0.1525,
   "y": 0.1,
   "w": 0.8475,
   "h": 0.9
  },
  "cutAspect": 0.7591
 },
 "prada-re-nylon-bucket-bag-black": {
  "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwDE2CBU3DA8IMtbeKwAAP7qo5EH0Rm6p/9luCCa+ROojlvjcAehqzwhElaqTNRtEZF1AIWnIoIswobGjzr08enpCKg+MtCVyflfWwAAAA==",
  "figure": true,
  "box": {
   "x": 0.1,
   "y": 0.142,
   "w": 0.9,
   "h": 0.658
  },
  "cutAspect": 1.0908
 },
 "louis-vuitton-x-supreme-keepall-bandouliere-45-red": {
  "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbAC06CHhShMQJBCA+VOsgAD+6oAppP0yeJxVkGm7Nrg0xdFGPfRHCLGO/FuznGCzfSiBldRLsIiyfOQ0Bi6uDwMc5Q7glDKTxOhjAVOepoUMAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.362,
   "w": 0.72,
   "h": 0.438
  },
  "cutAspect": 1.2962
 },
 "valentino-rockstud-glam-lock-grey": {
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZwDE2CKcmXwYAP7n6+kvokdtz4uBim/inL2RsHyMbMogR3DNFNRtnveL0xCnd3NtmvgzK0iDrcwAAAA=",
  "figure": true,
  "box": {
   "x": 0.1,
   "y": 0.089,
   "w": 0.9,
   "h": 0.711
  },
  "cutAspect": 1.012
 },
 "rolex-submariner-date-126613lb-bluesy": {
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JYwDCgCHhc7xELjW5AAD+6oDP4VUTbsiRGA0EWT/Y3AZBf7ggi4ukDg8pnKutpSGDdmSydfjpZYAA",
  "figure": false,
  "box": {
   "x": 0.2406,
   "y": 0.2,
   "w": 0.5188,
   "h": 0.6
  },
  "cutAspect": 0.6999
 },
 "rolex-datejust-41-chocolate-diamond": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwC2yCFsiFrVDq+QAP7qhRDjK33h8FLmcLoyUJllAiXvctXp9tYQYZ1pL/q/4+qFqtBg4kUcuVyorq/8xPv9G+eWsgAA",
  "figure": true,
  "box": {
   "x": 0.1294,
   "y": 0.07,
   "w": 0.7419,
   "h": 0.72
  },
  "cutAspect": 0.8314
 },
 "rolex-cosmograph-daytona-116505-everose": {
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZQDE2CHhS/HWflgA/uqAAO8A8ZFkpf9tW3L9MmSQXn1Yu3+AE3dWkXbzYxEAbxifjMHEWEWeUpp/AAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.454,
   "w": 0.72,
   "h": 0.346
  },
  "cutAspect": 1.6328
 },
 "rolex-cosmograph-daytona-126500ln-white": {
  "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwCw7Ypu33ap1/IsZ7AA/uqAz90rHJz+MbHyW5DcE5E9GGzM8nrRrEwFHguSryRAEchZ4s+k7x9ZXQ20f9mlRsG7MjsPvI1fgAAA",
  "figure": false,
  "box": {
   "x": 0.2113,
   "y": 0.2,
   "w": 0.5775,
   "h": 0.6
  },
  "cutAspect": 0.7771
 },
 "omega-speedmaster-moonwatch-professional": {
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZwC/OCHhTP0Qlv4AAP7qgA7zLFNyRXbt4v/GioIACIuEL5Qt8rj7r+FrVUcUm5jV/bpmZk2EIbL9WUNXNDQAAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.47,
   "w": 0.72,
   "h": 0.33
  },
  "cutAspect": 1.688
 },
 "omega-seamaster-diver-300m-blue": {
  "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAD5Dn1PqQcqLDo1IAA/uqVf/AjPclNR62ItReRsbtl8LFQt6hxUccSubKKG3FabENQ3DJSc0g2N4YHn/uSeNsFUgWJgWhJkYgFJ9NYeZk2DuSKvAAA",
  "figure": true,
  "box": {
   "x": 0.11,
   "y": 0.113,
   "w": 0.78,
   "h": 0.634
  },
  "cutAspect": 0.9849
 },
 "cartier-santos-de-cartier-medium": {
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZwDE2CHhcGQHHPLzAAD+6oDHkh4hepH7TtES/2Q6rmI6L34Yz5VzHIB4Uz7qwBfBA5NWkMIEq3QA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.3125,
   "w": 0.72,
   "h": 0.4875
  },
  "cutAspect": 1.1721
 },
 "cartier-roadster-chronograph": {
  "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwC7ABcR90fKMAD+6qOUtOqJ041p2Zln0g261G2TK3oOZZgrdbOROrIVgeLzPIMZaCMmbOdDUoSQWAcspr+JZZRBxvBzNLgwkBNf3wp3YAAA",
  "figure": true,
  "box": {
   "x": 0.195,
   "y": 0.07,
   "w": 0.6106,
   "h": 0.72
  },
  "cutAspect": 0.688
 },
 "cartier-tank-must-large": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAAW+gB8fKudgAA/u0+9u8fV1I8aHtHEHKVo/ALxlviwfRTeKsirkDluzvJo627olaIjbeqODqtsdeTVkfQt1EhgAAA",
  "figure": false,
  "box": {
   "x": 0.1781,
   "y": 0.2,
   "w": 0.6444,
   "h": 0.6
  },
  "cutAspect": 0.868
 },
 "patek-philippe-nautilus-5711-1a-blue": {
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoQABQAPu1kqU4ppaOiMAgBMB2JZwC7ACHhS8xoX+Egvs35AAD+6oAAmGxRCgNpOiRiM7PP5Wl71w/l75RojdTIBVSJa+0PMiuXzs3hJesUV4dsYAAAAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.503,
   "w": 0.72,
   "h": 0.297
  },
  "cutAspect": 1.8399
 },
 "audemars-piguet-royal-oak-15400or": {
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoQABQAPu1oqk6ppiQiMAgBMB2JZQAAW+9sTyDz71GDM4AA/up/35cYy5ZPs1W0oUQSeUYZwqKfW18Z1dNzyrM49WL3bIJOtcAAAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.5945,
   "w": 0.72,
   "h": 0.2055
  },
  "cutAspect": 2.5971
 },
 "breitling-navitimer-b01-chronograph-43": {
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAAW+zevNuAdESaExMgAP7qgOplbNbIkMKf2XHRZq5YIBPASdZebMTFmjy5urjEaqdHQ0u3uWqe8C51j96oxuBnjehluZaT8KwAAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.2295,
   "w": 0.72,
   "h": 0.5705
  },
  "cutAspect": 1.0091
 },
 "cartier-baignoire-allongee-vintage": {
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZwCAAAiu2QfRpBr6bNYAAP7qgM3tLfbS1Iu/N9bGxfo+nwIBJpZrxaz2jqqLsrPZDeAA",
  "figure": false,
  "box": {
   "x": 0.3438,
   "y": 0.2,
   "w": 0.3131,
   "h": 0.6
  },
  "cutAspect": 0.4319
 },
 "off-white-air-jordan-1-chicago-the-ten": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoQABQAPu1qrU8ppiQiMAgBMB2JYgC06CHhS9Kcz1AA/uqAAKmBgzUrqRjJF/OwPR1J4HpQgPK4s60JF3aG7poH+ObTSSag7wt8Rr7DclFEzfCgSJKkHMAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.4305,
   "w": 0.72,
   "h": 0.3695
  },
  "cutAspect": 1.5242
 },
 "air-jordan-1-low-se-navy-suede": {
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwCAAAgRcVc7CQgAAP7ql1cyzSIy/CPszCbesnjo2IN8GREnbMUVDxJBc5O9Mo4DJm75Nv+BK6h7hvAAAA==",
  "figure": true,
  "box": {
   "x": 0.2706,
   "y": 0,
   "w": 0.4594,
   "h": 0.74
  },
  "cutAspect": 0.5088
 },
 "air-jordan-1-retro-high-og-taxi": {
  "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQAAW+jLQDT831iycgAA/uqA2eCTG7oLdpESTokeDLfU3XEO3diByTtPVvQsLpI5X7vyr/Kyua0KSljhKqTVx8u6bnVxpOMqDwZUwhXcAAAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.2015,
   "w": 0.72,
   "h": 0.5985
  },
  "cutAspect": 0.9635
 },
 "air-jordan-1-low-og-bred-toe": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABQAPu1mqk4ppaOiMAgBMB2JZwC7ACHhS8zRxAi8AAD+6oAA6aqh8yHvaIUCLaZ17W173Ekh1AFow1/PiP+y/GfeXpfmx11F9pRzzg4iwizyqBcsKYAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.4365,
   "w": 0.72,
   "h": 0.3635
  },
  "cutAspect": 1.5417
 },
 "nike-dunk-low-panda": {
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwDDNYrwpK+wxwky4AD+6pD/rq096/IOwom+TXmQkeiuMvn5Bz67zCl3g9V+VNoEb7dPlrc6yZhs9HC++hXpE1PfA5jp5wbwzB2YAAA=",
  "figure": true,
  "box": {
   "x": 0.1688,
   "y": 0,
   "w": 0.6631,
   "h": 0.74
  },
  "cutAspect": 0.7292
 },
 "nike-sb-dunk-low-orange-mint": {
  "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBadBDwpbkq6G0i7x6AA/up/6H/tM2V/VJtsu9mDdUY1BQA+s9/jRkUlrgAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.5325,
   "w": 0.72,
   "h": 0.2675
  },
  "cutAspect": 2.0464
 },
 "adidas-yeezy-boost-350-v2-onyx": {
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwDE2CHiFQxjE1YIgAD+6n9AkILG140vsPv+LQYRx/J8dMBLBDWNqx/tFWhMe/LkCNvVomzceeCQd2H7WveMvSL+2AtvH2uT9KTnwAA=",
  "figure": true,
  "box": {
   "x": 0,
   "y": 0.167,
   "w": 1,
   "h": 0.633
  },
  "cutAspect": 1.2544
 },
 "adidas-yeezy-boost-350-v2-bone": {
  "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAgCdASoQABQAPu1krU2ppaSiMAgBMB2JZwC7ADKUAAD+72/5hDWm+bTk2Eqsc//KtN+gGGKK7hQA5FE+MHxanIAAAA==",
  "figure": true,
  "box": {
   "x": 0,
   "y": 0.3445,
   "w": 1,
   "h": 0.4555
  },
  "cutAspect": 1.7203
 },
 "adidas-yeezy-boost-750-light-grey": {
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoQABQAPu1kqk4ppaQiMAgBMB2JZwC/OCHhTPuyXQxwAP7qgBFtSKBWHGEeTT/F7I4RTg9O9yqin/8PzVAv+xehCMy/Llzbez+VoIZlAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.402,
   "w": 0.72,
   "h": 0.398
  },
  "cutAspect": 1.4153
 },
 "supreme-script-varsity-jacket-black": {
  "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAAWnSqVmmewSJrf87MAAD+6oUUjD7Ij/slWBl34/tNx1s/M9u/tmDt11n5vmCgEcY1QnJaW1TKBextRBxuH4j0bazWWPHon24lzBO9xabD6KZapJXPubxVJYyL9/ry8y03AgA=",
  "figure": true,
  "box": {
   "x": 0.05,
   "y": 0.133,
   "w": 0.9,
   "h": 0.867
  },
  "cutAspect": 0.8389
 },
 "balenciaga-political-campaign-hoodie-navy": {
  "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBACdASoQABQAPu1iqU2ppaQiMAgBMB2JQApggf8Bzm8ip+baDujL3rFDgAD+6pcE3szKqtjfzt/Q85ckyZLvn+ftJhNjNdc3dK67iNIpynnzO52t0JFRu2lKL0yjtKQDJq3WLu+FYs1vzyI13lkxg3ag0RDou43JuTgDt8P0OpsX4AA=",
  "figure": true,
  "box": {
   "x": 0.1244,
   "y": 0.1,
   "w": 0.7513,
   "h": 0.9
  },
  "cutAspect": 0.6759
 },
 "balenciaga-soccer-t-shirt-oversized": {
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZwDG9Buke812CRt66uDudAAA/u1fLxHjCjTNEm0iC8jtjGaOmTOVqH2HklNLZbbW5u11fC3KJ23zDN/LWOhY56kmiX7mUAjicui2sRunYXZMGxuORReKuiWOIGgA",
  "figure": true,
  "box": {
   "x": 0.2013,
   "y": 0.1,
   "w": 0.5981,
   "h": 0.9
  },
  "cutAspect": 0.543
 },
 "fear-of-god-essentials-hoodie-cloud-dancer": {
  "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoQABQAPu1iqU2ppaQiMAgBMB2JZwDE2C0kAAD+72k1thdgNSwVna8TWkQdcZgA",
  "figure": false,
  "box": {
   "x": 0.1625,
   "y": 0.07,
   "w": 0.6756,
   "h": 0.72
  },
  "cutAspect": 0.7631
 },
 "supreme-backpack-ss19-navy": {
  "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBjehDwud4h9xnHYAAD+6oDP7CpVug9kwUNjDqjqYtthO3J8F2JUW0FurMYBv9C7SoyfGHqwnGRlO/ZBqVBLXwADx1aRBS2AAA==",
  "figure": false,
  "box": {
   "x": 0.2225,
   "y": 0.2,
   "w": 0.555,
   "h": 0.6
  },
  "cutAspect": 0.7489
 },
 "burberry-kensington-heritage-trench-honey": {
  "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwC7ABo1zKyblDHvbZwAAP7h0JrKj+LPZxrS0zMubbl7lulDykiYGRSzUlVJ4+YDdPrqAojKdIMR7P8MuSYFjKs23+UZaVjX4Wf0u9FH2LP7Dvp+cuiyOeoK5hO8w4AAAA==",
  "figure": true,
  "box": {
   "x": 0.0094,
   "y": 0,
   "w": 0.9813,
   "h": 1
  },
  "cutAspect": 0.791
 },
 "max-mara-101801-icon-coat-camel": {
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQCsACHhcdWpWAq6kHoAAP7qgMmLOI0Sz+xrL6ZZosNl5ZzFC9OeLZTPE4lfCexeb5pwAAA=",
  "figure": false,
  "box": {
   "x": 0.3606,
   "y": 0.2,
   "w": 0.2788,
   "h": 0.6
  },
  "cutAspect": 0.3886
 },
 "max-mara-madame-coat-ivory": {
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZwC2yBwwxfYjU/jhfMvigAD9AfOi5OtvFBmymYJeSHTjEyZFkIeud7jMwSiPr/AKNutY4G7ytwf4WQA3TnxZQzayqQuLWo8cAE+pu7fT5gspDVIJY52N98WvmxAA",
  "figure": true,
  "box": {
   "x": 0,
   "y": 0,
   "w": 0.6594,
   "h": 1
  },
  "cutAspect": 0.5348
 },
 "brunello-cucinelli-cashmere-overcoat-camel": {
  "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZQC7ABuj6brhQtn7gAD+6pdxf362KAJ2mMdkfcp4IM8FjiT0lIcpRiLvHRuXoBu6D7PEQiCDFZRxxGnXBCoNr2afRevQOHBAurJFqS0AAA==",
  "figure": true,
  "box": {
   "x": 0.2488,
   "y": 0.1,
   "w": 0.5025,
   "h": 0.9
  },
  "cutAspect": 0.4582
 },
 "gucci-horsebit-1953-loafer-suede": {
  "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdACHhX/dsggD+6oDP3MEKr9e8GQcEOQ/tyIkB/wfNoqRZgYCiHIEMrYWAv83AhVqRnwGfH6qycqOCB5RVlDBBZsZoAAA=",
  "figure": false,
  "box": {
   "x": 0.2269,
   "y": 0.2,
   "w": 0.5463,
   "h": 0.6
  },
  "cutAspect": 0.7427
 },
 "santoni-horsebit-loafer-cognac": {
  "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBACdASoQABQAPu1iqU2ppaQiMAgBMB2JQBdmUAS1ov9+zZ+4CwvFnoG3AAD+6oBTUGKt2R5wXWIPq3OGsX/bfqpIt/Ep06rd7/Dytb/5rOWvsCRrV+3VT48AE/Yp/sKfJJCCGZMqAsOxemE2prhcqx7ZIdDF0AAAAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.3015,
   "w": 0.72,
   "h": 0.4985
  },
  "cutAspect": 1.1464
 },
 "christian-louboutin-dandelion-spikes-loafer": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoQABQAPu1iqk4ppaQiMAgBMB2JZwC7ACHhX8mbYggAAP7qgM/Xf9S1I/x1ALAF35iA7QV0BGb5rAl2TRl8uQP57Yfh/PieEbhKA758LM2YGC6VS+HKAAAA",
  "figure": false,
  "box": {
   "x": 0.2506,
   "y": 0.2,
   "w": 0.4994,
   "h": 0.6
  },
  "cutAspect": 0.6761
 },
 "saint-laurent-chelsea-boot-black": {
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoQABQAPu1kqk4ppaQiMAgBMB2JZwC/OCHhS8LTG1lOzzBYAAD+6n/+xDGVRdV3jKb0ZazA358umLdudyYD7bRIYkyt2uevsZx5U8f40XC1cNWdgAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.423,
   "w": 0.72,
   "h": 0.377
  },
  "cutAspect": 1.4808
 },
 "bottega-veneta-slouch-knee-boots": {
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABQAPu1kqU2ppaOiMAgBMB2JZwDCgYto33hs4RseyWAA/uqAzrcJicjUMh9vLxro37y77w5GaRZarqiT3I4yOAV2OmR9aHogj/PaNgclPtw1Kglpppl3d6Iw0P7iAAA=",
  "figure": false,
  "box": {
   "x": 0.1844,
   "y": 0.2,
   "w": 0.6319,
   "h": 0.6
  },
  "cutAspect": 0.8479
 },
 "tiffany-lock-bangle-yellow-gold-diamonds": {
  "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQAAW+9rpTIY6ZIAAP7qf+h+U+vaR7k5+ZnvVYjLvaBcSoc6orIAAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.5805,
   "w": 0.72,
   "h": 0.2195
  },
  "cutAspect": 2.3829
 },
 "clash-de-cartier-bracelet-rose-gold": {
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JQBOgBDwpblYkAAD+6oC9TC2lVybBp7iHwVHzreOBGgEFYgl0MHiuhYn8w8EHUVm4tw346RZQAA==",
  "figure": false,
  "box": {
   "x": 0.2806,
   "y": 0.2,
   "w": 0.4394,
   "h": 0.6
  },
  "cutAspect": 0.6031
 },
 "cartier-santos-aviator-sunglasses": {
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAwCdASoQABQAPu1kqk2ppaQiMAgBMB2JZwAAW+9q8yVHgAD+6n/cL8P/RSEHQbCU8HlR8k1b+Ecch3720hXGOrZd6rAPtw1KglsJzXL2aCoAAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.5935,
   "w": 0.72,
   "h": 0.2065
  },
  "cutAspect": 2.6457
 },
 "chanel-n5-eau-de-parfum-100ml": {
  "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwC7MoADTtMSkPuAAP7qgL2x76FqzPRbP02JlDWNbhJxInvX8HVbYx2Ns+FpEPfgAA==",
  "figure": false,
  "box": {
   "x": 0.2838,
   "y": 0.2,
   "w": 0.4331,
   "h": 0.6
  },
  "cutAspect": 0.5892
 },
 "bleu-de-chanel-eau-de-parfum-100ml": {
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAwCdASoQABQAPu1mq04ppaQiMAgBMB2JQBfnBDwplvdOZgD+6oDPsjhj5u9xJ/HahnlQj2otjFN/0fK1Pjcai3HJYhNw93xNjaGfOcnrR/QwiqIjIWepgAA=",
  "figure": false,
  "box": {
   "x": 0.2369,
   "y": 0.2,
   "w": 0.5263,
   "h": 0.6
  },
  "cutAspect": 0.7182
 },
 "gucci-logo-belt-bag-web": {
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoQABQAPu1yrU+pp6QiMAgBMB2JZwAAW+9sFyPPucDoAAD+6n/flH0dHbunJVNvyz9bPGtH5BIrP+q6O3YsILPYG32P7BsgAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.6465,
   "w": 0.72,
   "h": 0.1535
  },
  "cutAspect": 3.4231
 },
 "hermes-kelly-25-sellier-rouge-casaque": {
  "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBUehEAJ2T+wAAD+6nuSldqAwBNwCBiHp4ndXKQBuZfEueJm06w5VF+l0qncAIwDcmaXoUaWQHEmVzYsF6Fz1o34Nx4AAAA=",
  "figure": true,
  "box": {
   "x": 0.2788,
   "y": 0,
   "w": 0.4425,
   "h": 0.74
  },
  "cutAspect": 0.4917
 },
 "chanel-classic-double-flap-medium-black": {
  "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAAUoPVKT6it9n8tAAA/u1g/msEe3i8A6zzAdqecIiqYeWRmxcruge6rqWypqNFndhe6jYhMrcNZ+GHHFl6E++1w7tiL8S8il5MmRyqVkPNLHUmjQ1RQr37o4AA",
  "figure": true,
  "box": {
   "x": -0.0044,
   "y": 0,
   "w": 1.0094,
   "h": 1
  },
  "cutAspect": 0.8157
 },
 "louis-vuitton-pochette-metis-monogram": {
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwCdACHwwgpb42gAAP7ne9WHvwSFhtWnUGFts5UMqGfVTypFqVSSKbNPUMEi2EjpRRLSjZytsAAA",
  "figure": true,
  "box": {
   "x": 0,
   "y": 0.07,
   "w": 0.7156,
   "h": 0.72
  },
  "cutAspect": 0.8008
 },
 "lady-dior-medium-natural-cannage-raffia": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAwCdASoQABQAPu1iqk4ppaQiMAgBMB2JZAC06CHhS0R6gAD+6oC573BczF2sy4OElVwS0/F0yzNuRegfSVhocxwGTJZpkE0VqBkwyWKvUUolRwQPN9g1QshZjuAA",
  "figure": false,
  "box": {
   "x": 0.1613,
   "y": 0.2,
   "w": 0.6781,
   "h": 0.6
  },
  "cutAspect": 0.9076
 },
 "gucci-blondie-shoulder-bag-pink": {
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoQABQAPu1iqU2ppaQiMAgBMB2JZQC06CHhcLBcbvxVoHb8QAD+6oCf2y4yjG3pgR+K9m9B7yVBnGoXiOYBup1vLCue1y721NTjyYaCXvjl4AAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.24,
   "w": 0.72,
   "h": 0.56
  },
  "cutAspect": 1.0272
 },
 "gucci-ophidia-mini-hobo": {
  "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZwAATrSubOvXGMuLOAD+mJPeRG3zSn8c04bJGJAZzc0pQpzza1/E1BtGqz+KUurK/fMY9Wc3Amk0Gty4jLt0ozijMK3iRx1tsgw2J8hYtfpvJNoYj5CVlWPoA9/febdP962w+KuTmGU96aainQAA",
  "figure": true,
  "box": {
   "x": -0.0075,
   "y": 0,
   "w": 1.0156,
   "h": 1
  },
  "cutAspect": 0.8201
 },
 "prada-cahier-shoulder-bag-silver": {
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZwC7ACHfpnjsIb344AAA/uqAJRx0XqiAiYe8iNRs0epl08y/m++sWr14PLb6oUwsxiYJhRL2JpDQOgm1zkSnEzRlcpAA",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.3235,
   "w": 0.72,
   "h": 0.4765
  },
  "cutAspect": 1.1998
 },
 "rolex-submariner-date-126610ln": {
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoQABQAPu1kqk4ppaQiMAgBMB2JZwC/OCHhTHyKyeAA/uqAz0+iya2vpHUrNKO+WS2kgng5t+B+wHy1mqkifuTm7TtmTXY0IqyQAA==",
  "figure": false,
  "box": {
   "x": 0.3025,
   "y": 0.2,
   "w": 0.395,
   "h": 0.6
  },
  "cutAspect": 0.5443
 },
 "air-jordan-1-retro-high-og-lost-and-found": {
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoQABQAPu1iqk2ppaQiMAgBMB2JZAC7MoADTtE3FHpopIAA/up/8vvV3pxpmFzZkeuDGk3yd6hQHrjodRzIl262pCfS8Jt7drFIPlfYJUUgNWMLZqAAAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.399,
   "w": 0.72,
   "h": 0.401
  },
  "cutAspect": 1.4109
 },
 "off-white-nike-air-force-1-university-gold": {
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoQABQAPu1kqk2ppaQiMAgBMB2JbAC06CHhS2OOvyVyJgAA/up/8EnAVMhKvlbKQ2EWxdL0+gBY9yyLd6WbbQPhXp65VA4gAAA=",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.5125,
   "w": 0.72,
   "h": 0.2875
  },
  "cutAspect": 1.9193
 },
 "balenciaga-triple-s-white": {
  "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABwAwCdASoQABQAPu1kq04ppaQiMAgBMB2JZQC/OB6NskveKAAA/uqWyUvt1LyLCsFdebUDQLGT6txe9JsH9/Q7AEyLVAAA",
  "figure": true,
  "box": {
   "x": 0.2294,
   "y": 0,
   "w": 0.5419,
   "h": 0.8
  },
  "cutAspect": 0.5529
 },
 "vlone-friends-hoodie-black": {
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAwCdASoQABQAPu1kqk4ppaQiMAgBMB2JZwAAW+9u0ywAAP7qgM31VU7yBIIX7T8E4+6nmlbSrcHUfRXPCXpuHcBtmTYWE4lhWAAA",
  "figure": false,
  "box": {
   "x": 0.3875,
   "y": 0.2,
   "w": 0.2256,
   "h": 0.6
  },
  "cutAspect": 0.3156
 },
 "rimowa-x-supreme-topas-multiwheel-82": {
  "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoQABQAPu1iqk2ppaQiMAgBMB2JYgC7ACHhTqW6SeB18A86AAD+6oAJTpJb9ojewtYhywyAqnRIlGtf+tWFWgOHWxAy6s2qRdB2vUX+lBY28PlQ2CHqtFajkGVhySUSZrwRSDR+ZTrbHMYAmdTsmqcHSfx1DEqWY9woAA==",
  "figure": true,
  "box": {
   "x": 0.05,
   "y": 0.542,
   "w": 0.9,
   "h": 0.458
  },
  "cutAspect": 1.5373
 },
 "hermes-carre-90-chaine-dancre-violet": {
  "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgC7ACHiEpGhg5LZlzNdQAD+7TiX61RIzxa/fW4HDeBDzNCS9wTKQP6L7ZTtGTAYM8bqhPFaXH26jymaTU1bY5ryIwP8ccTRTbZSebKnxAjPHvNgaVf3KQAAAA==",
  "figure": true,
  "box": {
   "x": 0.14,
   "y": 0.224,
   "w": 0.72,
   "h": 0.576
  },
  "cutAspect": 1
 },
 "prada-linea-rossa-sunglasses-black": {
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoQABQAPu1mqk2ppaQiMAgBMB2JZwC/OCHhSw/SLxQAAP7qf+h+WP8KGncyWPDBQ+4GbNJLlWpdxw+TZvwPGzsZDlZJeLc+IcFAAA==",
  "figure": false,
  "box": {
   "x": 0.14,
   "y": 0.591,
   "w": 0.72,
   "h": 0.209
  },
  "cutAspect": 2.5968
 }
};
